[package]
name = "outsource"
version = "0.1.0"
edition = "2021"
#build = "build.rs"

[dependencies]
rand = "0.8.5"
sha2 = "0.10.8"

# Minimise binary size a bit
[profile.release]
strip = true
lto = true
